// // <auto-generated />
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
// using P8.Server.DB;

// namespace P8.Server.Migrations
// {
//     [DbContext(typeof(InstrumentDbContext))]
//     partial class InstrumentDbContextModelSnapshot : ModelSnapshot
//     {
//         protected override void BuildModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("Relational:MaxIdentifierLength", 63)
//                 .HasAnnotation("ProductVersion", "5.0.7")
//                 .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

//             modelBuilder.Entity("P8.Shared.Instrument", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("integer")
//                         .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

//                     b.Property<string>("ImgAddress")
//                         .HasColumnType("text");

//                     b.Property<int>("LeftInStock")
//                         .HasColumnType("integer");

//                     b.Property<string>("Name")
//                         .HasColumnType("text");

//                     b.Property<int>("Price")
//                         .HasColumnType("integer");

//                     b.HasKey("Id");

//                     b.ToTable("Instruments");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
